title: Weebarr Docs
description: Seasonal anime discovery and request dashboard for Seerr or Sonarr Direct
version: 0.1.85
markdown: kramdown
permalink: pretty
baseurl: /weebarr
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
