title: Weebarr Docs
description: Seasonal anime discovery and request management for Seerr and Sonarr Direct
markdown: kramdown
permalink: pretty
baseurl: /weebarr
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
